### ISSUE TITLE
Google code 429 error & Connection timeout

### ISSUE THREAD

**Issue by philbywalsh** [joweich/year-in-search-trends#3]
This is an amazing data viz repo. Well done @joweich !

**Summary:** After 2 successful runs I got a Google code 429 error & then, after making changes to the TrendReq () parameters I kept getting Connection timeout errors.

The issue I have is, after running this script twice successfully (with an output image generated both times) I then encountered a Google "code 429" error.

**python yearinsearchtrends.py**

Traceback (most recent call last):
  File "yearinsearchtrends.py", line 141, in <module>
    import yearinsearchtrends as yist
  File "C:\Users\Philip\Documents\Python\Projects\4. Misc Data Analysis\Google search year trends (joweich)\yearinsearchtrends.py", line 145, in <module>
    keywords, "2022-01-01 2023-01-01"
  File "C:\Users\Philip\Documents\Python\Projects\4. Misc Data Analysis\Google search year trends (joweich)\yearinsearchtrends.py", line 44, in get_interest_over_time
    df_chunk = pytrends.interest_over_time()
  File "C:\Users\Philip\Miniconda3\lib\site-packages\pytrends\request.py", line 230, in interest_over_time
    params=over_time_payload,
  File "C:\Users\Philip\Miniconda3\lib\site-packages\pytrends\request.py", line 160, in _get_data
    response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 429.

After reading up a bit on this error [here](https://github.com/GeneralMills/pytrends) I amended this line:

pytrends = TrendReq(tz=360)

to this...

`pytrends = TrendReq(hl='en-US', tz=360, timeout=(12.03,25), proxies=['https://34.203.233.13:80',], retries=10, backoff_factor=0.5, requests_args={'verify':False})`

But got the error below as a result

`Traceback (most recent call last):
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000011D5CC7CC48>, 'Connection to 35.201.123.31 timed out. (connect timeout=12.03)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Philip\Miniconda3\lib\site-packages\requests\adapters.py", line 450, in send
    timeout=timeout
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Philip\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000011D5CC7CC48>, 'Connection to 35.201.123.31 timed out. (connect timeout=12.03)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yearinsearchtrends.py", line 144, in <module>
    import yearinsearchtrends as yist
  File "C:\Users\Philip\Documents\Python\Projects\4. Misc Data Analysis\Google search year trends (joweich)\yearinsearchtrends.py", line 148, in <module>
    keywords, "2022-01-01 2023-01-01"
  File "C:\Users\Philip\Documents\Python\Projects\4. Misc Data Analysis\Google search year trends (joweich)\yearinsearchtrends.py", line 43, in get_interest_over_time
    pytrends = TrendReq(hl='en-US', tz=360, timeout=(12.03,25), proxies=['https://35.201.123.31:880',], retries=10, backoff_factor=0.5, requests_args={'verify':False})
  File "C:\Users\Philip\Miniconda3\lib\site-packages\pytrends\request.py", line 55, in __init__
    self.cookies = self.GetGoogleCookie()
  File "C:\Users\Philip\Miniconda3\lib\site-packages\pytrends\request.py", line 90, in GetGoogleCookie
    **self.requests_args
  File "C:\Users\Philip\Miniconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Philip\Miniconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Philip\Miniconda3\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Philip\Miniconda3\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Philip\Miniconda3\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000011D5CC7CC48>, 'Connection to 35.201.123.31 timed out. (connect timeout=12.03)'))`

**Comment by joweich** [comment]
Hi @philbywalsh, this is not an error of this module.
It's rather a self-protection mechanism by the respective endpoint to prevent abuse. Keep in mind that neither this project nor pytrends are officially supported tools and pytrends itself is only a pseudo-api.
Waiting for some time will usually unblock your session.
